### ISSUE TITLE
Incorrect definition for m.ln1p

### ISSUE THREAD

**Issue by jthompson6** [opendatagroup/hadrian#10]
The spec for the function
`m.ln1p` defines it as `ln(1+ x^2)`. This is surprising because the normal definition, is `ln(1+ x)`. This aligns with the classic Taylor series (the Mercator series) and `java.lang.Math.log1p`.

Looking at the code for hadrian, I see that the implementation is actually `java.lang.Math.log1p`.

I can verify this by running the PFA script
```
input: double
output: {type: array, items: double}
action:
  - new: [{m.ln1p: [input]}, {m.ln: [{+: [1, input]}]}, {m.ln: [{+: [1, {"**": [input, 2]}]}]}]
    type: {type: array, items: double}
```
and seeing the that the output for the first value matches the second, not the third.

So I think we should change the spec to say `ln(1+ x)`.
